spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  application:
    name: lecture02
  security:
    user:
      name: user
      password: user
      roles: USER
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email


logging:
  file:
    name: logs/myapp.log
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: TRACE

management:

  tracing:
    sampling:
      probability: 1.0
#  opentelemetry:
#    tracing:
#      export:
#        otlp:
#          endpoint: http://localhost:4318/v1/traces
#  otlp:
#    metrics:
#      export:
#        url: http://localhost:4318/v1/traces
#        enabled: true
jdbc:
  datasource-proxy:
    enabled: true
  includes: connection, query, fetch
